baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Bootstrappy Site"
theme = "mybootstraptheme"

relativeURLs = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    
  [[menu.main]]
    identifier = "foo"
    name = "Foo"
    url = "/foo/"
    
    

