baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Bootstrappy Site"
# theme = "mybootstraptheme"
theme = "silk-roads-hugo-theme"

relativeURLs = true

[menu]
  # [[menu.main]]
  #   identifier = "home"
  #   name = "Home"
  #   url = "/"
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "login"
    name = "Login"
    url = "/login/"
    
    

